In [38]:
import pandas as pd
import numpy as np

In [39]:
def get_dataset():
    print('Loading Dataset')
    #Importing Data from CSV file
    data=pd.read_csv("heart.csv")
#     labels=data.iloc[:,[0]].values
#     pixels=data['pixels']

#     #converting pixels to Gray Scale images of 48X48 
#     images = np.array([np.fromstring(pixel, dtype=int, sep=" ")for pixel in pixels])
#     #images=images/255.0 #normalize images between [0,1]
#     images = images.reshape(images.shape[0],48,48).astype('float32')
#     return images, labels
    return data

In [40]:
data = get_dataset()

Loading Dataset

In [47]:
data_copy = data.copy()
sex = set(data['Sex'])
chestPainType = set(data['ChestPainType'])
restingECG = set(data['RestingECG'])
exerciseAngina = set(data['ExerciseAngina'])
ST_Slope = set(data['ST_Slope'])

In [48]:
print(sex)
print(chestPainType)
print(restingECG)
print(exerciseAngina)
print(ST_Slope)

{'F', 'M'}
{'ASY', 'TA', 'NAP', 'ATA'}
{'LVH', 'Normal', 'ST'}
{'N', 'Y'}
{'Up', 'Flat', 'Down'}

In [49]:
count = 0
for s in sex:
    data_copy['Sex']= data_copy['Sex'].replace([s], count)
    count +=1
    
count = 0
for c in chestPainType:
    data_copy['ChestPainType']= data_copy['ChestPainType'].replace([c], count)
    count +=1
    
count = 0
for r in restingECG:
    data_copy['RestingECG']= data_copy['RestingECG'].replace([r], count)
    count +=1
count = 0
for e in exerciseAngina:
    data_copy['ExerciseAngina']= data_copy['ExerciseAngina'].replace([e], count)
    count +=1
count = 0
for s in ST_Slope:
    data_copy['ST_Slope']= data_copy['ST_Slope'].replace([s], count)
    count +=1
data_copy

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,3,140,289,0,1,172,0,0.0,0,0
1,49,0,2,160,180,0,1,156,0,1.0,1,1
2,37,1,3,130,283,0,2,98,0,0.0,0,0
3,48,0,0,138,214,0,1,108,1,1.5,1,1
4,54,1,2,150,195,0,1,122,0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,1,110,264,0,1,132,0,1.2,1,1
914,68,1,0,144,193,1,1,141,0,3.4,1,1
915,57,1,0,130,131,0,1,115,1,1.2,1,1
916,57,0,3,130,236,0,0,174,0,0.0,1,1
917,38,1,2,138,175,0,1,173,0,0.0,0,0

In [51]:
num_list= ["Age","RestingBP","Cholesterol","FastingBS","MaxHR","Oldpeak", 'ChestPainType','RestingECG','ST_Slope']
for i in num_list:
    mean = data_copy[i].mean()
    std = data_copy[i].std()
    data_copy[i] = (data_copy[i]-mean)/std
data_copy

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,-1.432359,1,1.578730,0.410685,0.824621,-0.551041,0.017245,1.382175,0,-0.831979,-1.051541,0
1,-0.478223,0,0.765901,1.490940,-0.171867,-0.551041,0.017245,0.753746,0,0.105606,0.595753,1
2,-1.750404,1,1.578730,-0.129442,0.769768,-0.551041,1.600347,-1.524307,0,-0.831979,-1.051541,0
3,-0.584238,0,-0.859757,0.302660,0.138964,-0.551041,0.017245,-1.131539,1,0.574398,0.595753,1
4,0.051853,1,0.765901,0.950812,-0.034736,-0.551041,0.017245,-0.581664,0,-0.831979,-1.051541,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,-0.902283,1,-0.046928,-1.209697,0.596068,-0.551041,0.017245,-0.188897,0,0.293123,0.595753,1
914,1.536064,1,-0.859757,0.626736,-0.053020,1.812770,0.017245,0.164595,0,2.355810,0.595753,1
915,0.369898,1,-0.859757,-0.129442,-0.619830,-0.551041,0.017245,-0.856602,1,0.293123,0.595753,1
916,0.369898,0,1.578730,-0.129442,0.340090,-0.551041,-1.565856,1.460728,0,-0.831979,0.595753,1
917,-1.644389,1,0.765901,0.302660,-0.217578,-0.551041,0.017245,1.421452,0,-0.831979,-1.051541,0

In [52]:
data_np = data_copy.to_numpy()

In [53]:
np.save('heart_convert2', data_np)